<?php
require_once __DIR__ . '/includes/app.php';
requireRole(['project_manager', 'team_member']);

$user = currentUser();

if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    $action = $_POST['action'] ?? '';
    if ($action === 'mark_read') {
        markAllNotificationsRead((int)$user['id']);
        setFlash('success', 'All notifications marked as read.');
    } elseif ($action === 'clear_all') {
        clearAllNotifications((int)$user['id']);
        setFlash('success', 'All notifications cleared.');
    }
    header('Location: notifications.php');
    exit;
}

$notes = userNotifications((int)$user['id']);
$title = 'Notifications - WorkFlowTrack Prototype';
require __DIR__ . '/templates/header.php';
?>
<div class="page-header">
    <div>
        <h1>Notification Center</h1>
        <p>Assignment alerts and workflow updates generated by the prototype.</p>
    </div>
    <div class="row-actions">
        <form method="post" style="display:inline-block;">
            <input type="hidden" name="action" value="mark_read">
            <button type="submit" class="btn btn-secondary">Mark as Read</button>
        </form>
        <form method="post" style="display:inline-block;">
            <input type="hidden" name="action" value="clear_all">
            <button type="submit" class="btn btn-danger">Clear All</button>
        </form>
    </div>
</div>

<section class="panel">
    <?php if (empty($notes)): ?>
        <div class="empty-state">No notifications yet. Create or update a task to generate one.</div>
    <?php else: ?>
        <div class="note-list">
            <?php foreach ($notes as $note): ?>
                <div class="note-item">
                    <strong><?= e($note['message']) ?></strong>
                    <div class="note-meta">
                        <?= e($note['created_at']) ?> · <?= $note['is_read'] ? 'Read' : 'Unread' ?>
                    </div>
                </div>
            <?php endforeach; ?>
        </div>
    <?php endif; ?>
</section>
<?php require __DIR__ . '/templates/footer.php'; ?>
